"""init

Revision ID: 445860bca3bc
Revises:
Create Date: 2025-12-16 23:52:51.159282

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "445860bca3bc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_catogories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "positions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("salary", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "employees",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_items",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["item_catogories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.execute("""
   INSERT INTO
   POSITIONS (
       NAME,
       SALARY,
       ID,
       CREATED_AT,
       UPDATED_AT,
       DELETED_AT
   )
VALUES
   (
       'Бармен',
       400,
       '5e9f732c-0eb4-4d6e-87a6-67b1c0a5ca1c',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   ),
   (
       'Официант',
       400,
       'efcc882e-c4d9-451f-be7c-ea2ec94f7706',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   ),
   (
       'Администратор',
       400,
       '7d23f503-34e4-4aa7-a0bd-66ecb6d74090',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   ),
   (
       'Охранник',
       400,
       '7833ab2e-7ae1-4843-baf5-dc620d442bba',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   )
   """)
    op.execute("""
   INSERT INTO
   PUBLIC.EMPLOYEES (
       ID,
       FIRST_NAME,
       LAST_NAME,
       PATRONYMIC,
       POSITION_ID,
       CREATED_AT,
       UPDATED_AT,
       DELETED_AT
   )
VALUES
   (
       'a1b2c3d4-e5f6-7890-1234-567890abcdef',
       'Рахим',
       'Рахимович',
       'Рахимов',
       '5e9f732c-0eb4-4d6e-87a6-67b1c0a5ca1c',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   ),
   (
       'fedcba98-7654-3210-fedc-ba9876543210',
       'Тимур',
       'Тимурович',
       'Тимуров',
       'efcc882e-c4d9-451f-be7c-ea2ec94f7706',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   ),
   (
       '01234567-89ab-cdef-0123-456789abcdef',
       'Маша',
       'Машовна',
       'Машова',
       'efcc882e-c4d9-451f-be7c-ea2ec94f7706',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   ),
   (
       '89914345-df3c-4bd9-8db9-02bb5ea2ea83',
       'Ангелина',
       'Ангелиновна',
       'Ангелинова',
       '7d23f503-34e4-4aa7-a0bd-66ecb6d74090',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   ),
   (
       '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
       'Данил',
       'Данилович',
       'Данилов',
       '7833ab2e-7ae1-4843-baf5-dc620d442bba',
       '2025-12-14 21:39:36.780170',
       '2025-12-14 21:39:36.780170',
       DEFAULT
   )
   """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menu_items")
    op.drop_table("employees")
    op.drop_table("positions")
    op.drop_table("item_catogories")
    # ### end Alembic commands ###
