"""new tables

Revision ID: 6e9cde1bd4cf
Revises: 6950b59bd044
Create Date: 2025-12-16 22:50:51.728375

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e9cde1bd4cf"
down_revision: Union[str, None] = "6950b59bd044"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("salary", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_positions_id"), "positions", ["id"], unique=False)
    op.create_table(
        "employees",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")

    op.execute("""
    INSERT INTO
	POSITIONS (
		NAME,
		SALARY,
		ID,
		CREATED_AT,
		UPDATED_AT,
		DELETED_AT
	)
VALUES
	(
		'Бармен',
		400,
		'5e9f732c-0eb4-4d6e-87a6-67b1c0a5ca1c',
		'2025-12-14 21:39:36.780170',
		'2025-12-14 21:39:36.780170',
		DEFAULT
	),
	(
		'Официант',
		400,
		'efcc882e-c4d9-451f-be7c-ea2ec94f7706',
		'2025-12-14 21:39:36.780170',
		'2025-12-14 21:39:36.780170',
		DEFAULT
	),
	(
		'Администратор',
		400,
		'7d23f503-34e4-4aa7-a0bd-66ecb6d74090',
		'2025-12-14 21:39:36.780170',
		'2025-12-14 21:39:36.780170',
		DEFAULT
	),
	(
		'Охранник',
		400,
		'7833ab2e-7ae1-4843-baf5-dc620d442bba',
		'2025-12-14 21:39:36.780170',
		'2025-12-14 21:39:36.780170',
		DEFAULT
	)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("login", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("users_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "login",
            name=op.f("users_login_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_positions_id"), table_name="positions")
    op.drop_table("positions")
    # ### end Alembic commands ###
